@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true

title System Sequence Diagram (SSD)

autonumber

actor Administrator
participant ":System" as System

activate Administrator
    Administrator -> System : starts the process of getting a list of employees with a given function/role
    activate System
        System --> Administrator : requests the specified function/role
    deactivate System

    Administrator -> System : provides the specified function/role
    activate System
        System --> Administrator : generates and displays the list of employees with the specified function/role
    deactivate System

    Administrator -> System : reviews the list of employees
        activate System
            System --> Administrator : may request additional details or filter criteria
        deactivate System

        Administrator -> System : confirms that the registration it's complete
        activate System
            System --> Administrator : provides feedback and notifies the success of the operation
        deactivate System
    deactivate Administrator

@enduml