@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor Administrator
participant ":System" as System

activate Administrator
    Administrator -> System : starts the process of registering an employee
    activate System
        System --> Administrator : requests employee information
    deactivate System

    Administrator -> System : provides employee information
    activate System
        System --> Administrator : validates and requests for employee documentation
    deactivate System

    Administrator -> System : provides employee documentation information
        activate System
            System --> Administrator : validates and asks for confirmation
        deactivate System

        Administrator -> System : confirms employee registration
        activate System
            System --> Administrator : records the information and notifies the success of the operation
        deactivate System
    deactivate Administrator

@enduml